### PR TITLE
fix: the correct way to use `nuxt-swiper`

### PR DESCRIPTION
**Pull request by cpreston321**
As the `Author` of **nuxt-swiper** I wanted to show the correct way to use the module itself. 

if you have any questions feel free to ask!

Thanks 💚

### CODE REVIEW

**Comment by thefubon** [comment]
Thanks! Cool!

**Comment by cpreston321** [comment]
@thefubon 

If you have any other questions about the module feel free to ask!

**Comment by thefubon** [comment]
Please tell me how to make Swiper navigation buttons outside of the container

**Comment by cpreston321** [comment]
@thefubon This is actually a limitation with vue package of `Swiper` that can't be possible that I found ATM. If anything I would ask upstream.

**Pull request merged**
